---

workspace:
  base: /build
  path: .

pipeline:
  build:
    image: rust:1.26.0
    environment:
      - CARGO_HOME=/build/.cargo
      - RUSTUP_HOME=/build/.multirust
    commands:
      - rustup default nightly
      - cargo check
      - cargo test

