---

workspace:
  base: /build
  path: .

pipeline:
  build:
    image: rust:1.26.0
    environment:
      - CARGO_HOME=/build/.cargo
      - RUSTUP_HOME=/build/.multirust
    commands:
      - apt-get update -y && apt-get install -y python3-dev
      - rustup default nightly
      - cargo check
      - cargo test

cache:
  mount:
    - .cargo
    - .multirust
    - target
