---

workspace:
  base: /build
  path: .

pipeline:
  build:
    image: rust:1.26.0
    environment:
      - CARGO_HOME=/build/.cargo
      - RUSTUP_HOME=/build/.multirust
    commands:
      - apt-get update -y && apt-get install -y python3-dev libssl-dev pkg-config cmake zlib1g-dev
      - rustup default nightly
      - cargo check
      - cargo test
      - RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
      - cargo tarpaulin --coveralls ${COVERALLS_TOKEN}
