[package]
name = "libosu"
version = "0.0.13"
authors = [
    "Michael Zhang <mail@mzhang.io>",
    "Nobbele <realnobbele@gmail.com>",
    "Ian <IanShehadeh2020@gmail.com>",
]
edition = "2018"

description = "General-purpose osu! library."
license = "MIT"
readme = "README.md"
keywords = ["osu"]
repository = "https://github.com/iptq/libosu.git"
documentation = "https://docs.rs/libosu/"

[dev-dependencies]
serde_json = "1.0.61"
difference = "2.0.0"
structopt = "0.3.21"

[dependencies]
anyhow = "1.0.37"
bitflags = "1.2.1"
lazy_static = "1.4.0"
num = "0.3.1"
num-derive = "0.3.3"
num-rational = "0.3.2"
num-traits = "0.2.14"
regex = "1.4.2"
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.61"
thiserror = "1.0.23"

hyper = { version = "0.14.2", features = ["stream", "http2", "client", "tcp"], optional = true }
hyper-tls = { version = "0.5.0", optional = true }
futures = { version = "0.3.8", optional = true }
tokio = { version = "1.0.1", optional = true }
xz2 = { version = "0.1.6", optional = true }
http = { version = "0.2.2", optional = true }
ordered-float = "2.0.1"

[features]
default = []
apiv1 = ["hyper", "hyper-tls", "tokio", "http", "futures"]
replay = ["xz2"]

# Used to check for clippy lints
# See: https://github.com/rust-lang/cargo/issues/8075#issuecomment-610259732
clippy = []
