[package]
name = "libosu"
version = "0.0.21"
authors = [
    "Michael Zhang <mail@mzhang.io>",
    "Nobbele <realnobbele@gmail.com>",
    "Ian <IanShehadeh2020@gmail.com>",
]
edition = "2018"

description = "General-purpose osu! library."
license = "MIT"
readme = "README.md"
keywords = ["osu"]
repository = "https://github.com/iptq/libosu.git"
documentation = "https://docs.rs/libosu/"

[package.metadata.docs.rs]
all-features = true

[dev-dependencies]
serde_json = "1.0.61"
difference = "2.0.0"
structopt = "0.3.21"
anyhow = "1.0.38"

[dependencies]
bitflags = "1.2.1"
lazy_static = "1.4.0"
num = "0.3.1"
num-derive = "0.3.3"
num-rational = "0.3.2"
num-traits = "0.2.14"
ordered-float = { version = "2.0.1", features = ["serde"] }
regex = "1.4.3"
thiserror = "1.0.23"
derive_more = "0.99.11"
log = "0.4.13"
byteorder = "1.4.2"

futures = { version = "0.3.12", optional = true }
http = { version = "0.2.3", optional = true }
hyper = { version = "0.14.2", features = ["stream", "http2", "client", "tcp"], optional = true }
hyper-tls = { version = "0.5.0", optional = true }
tokio = { version = "1.0.2", optional = true }
xz2 = { version = "0.1.6", optional = true }
serde = { version = "1.0.120", features = ["derive"], optional = true }
serde_json = { version = "1.0.61", optional = true }

[features]
default = []
apiv1 = ["hyper", "hyper-tls", "tokio", "http", "futures", "serde", "serde_json"]
replay-data = ["xz2"]

# Used to check for clippy lints
# See: https://github.com/rust-lang/cargo/issues/8075#issuecomment-610259732
clippy = []

[package.metadata.cargo-all-features]
skip_optional_dependencies = true
