[package]
name = "libosu"
version = "0.0.10"
authors = ["Michael Zhang <mail@mzhang.io>"]
edition = "2018"

description = "General-purpose osu! library."
license = "MIT"
readme = "README.md"
keywords = ["osu"]
repository = "https://github.com/iptq/libosu.git"
documentation = "https://docs.rs/libosu/"

[dev-dependencies]
serde_json = "1.0.60"
difference = "2.0.0"

[dependencies]
anyhow = "1.0.36"
futures = "0.3.8"
lazy_static = "1.4.0"
num = "0.3.1"
num-derive = "0.3.3"
num-rational = "0.3.2"
num-traits = "0.2.14"
regex = "1.4.2"
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.60"
thiserror = "1.0.22"

hyper = { version = "0.13.9", features = ["stream"], optional = true }
hyper-tls = { version = "0.4.3", optional = true }
tokio = { version = "1.0.1", optional = true }
xz2 = { version = "0.1.6", optional = true }
http = { version = "0.2.2", optional = true }

[features]
default = []
apiv1 = ["hyper", "hyper-tls", "tokio", "http"]
replay = ["xz2"]

# Used to check for clippy lints
# See: https://github.com/rust-lang/cargo/issues/8075#issuecomment-610259732
clippy = []
