[package]
name = "libosu"
version = "0.0.0"
authors = ["michael <localhost>"]

description = "General-purpose osu! library with bindings for other languages."
license = "MIT"
readme = "README.md"
keywords = ["osu"]
repository = "https://github.com/iptq/libosu.git"
documentation = "https://docs.rs/libosu/"

[dependencies]
