[package]
name = "libosu-py"
version = "0.1.0"
authors = ["Michael <localhost>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.2.7", features = ["extension-module"] }
libosu = { version = "0.0", path = "../libosu" }

